<a href="https://colab.research.google.com/github/Nermeen-Moussa/ML-DL-Reference-Guide/blob/machine-learning/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**a resampling technique used to evaluate how well a machine learning model generalizes to unseen data while preventing overfitting.**



1.   Prevents Overfitting: It ensures the model does not just memorize the specific training split.

2.   Reliable Evaluation: Provides a highly stable estimate of model performance compared to a single train-test split.

3.   Maximizes Data Utility: Every sample gets used for evaluation, which is vital for smaller datasets.


**Its techniques:
1. K-Fold=> Splits data into K equal parts (folds), Standard regression and balanced classification tasks.

2. Stratified K-Fold=> Follows the K-Fold process, Imbalanced classification datasets.


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.linear_model import LogisticRegression

In [2]:
np.random.seed(42)
fastball_speed=np.random.randint(90,106,size=500)
tommy_john=np.where(fastball_speed>96,np.random.choice([0,1],size=500,p=[0.3,0.7]),0)
d={'fastball_speed':fastball_speed,'tommy_john':tommy_john}
df=pd.DataFrame(data=d)
X=df[['fastball_speed']]
y=df[['tommy_john']]

In [3]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [4]:
# .values=> converts the pandas dataframe into a raw numpy array
# .ravel=>  Flattens the multi-dimensional array into a continuous 1D array
lr=LogisticRegression()
lr.fit(X_train,y_train.values.ravel())
lr.score(X_test,y_test)

0.81

In [14]:
X1_train,X1_test,y1_train,y1_test=train_test_split(X,y,test_size=0.2,random_state=11)

In [15]:
lr.fit(X1_train,y1_train.values.ravel())
lr.score(X1_test,y1_test)

0.71

In [16]:
cvscore=cross_val_score(lr,X,y.values.ravel(),cv=10)
cvscore

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [17]:
np.average(cvscore)

np.float64(0.756)

In [18]:
np.std(cvscore)

np.float64(0.04270831300812523)

In [20]:
#cv=>"cross validation",  average accuracy score calculated across all test rounds to give a stable measure of model performance.
# shuffle=> reorder the data.
kf=KFold(n_splits=15,shuffle=True,random_state=42)
kfscore=cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='f1')
kfscore

array([0.66666667, 0.82758621, 0.72727273, 0.7027027 , 0.6875    ,
       0.72727273, 0.74074074, 0.72      , 0.66666667, 0.60869565,
       0.66666667, 0.63157895, 0.64516129, 0.66666667, 0.6       ])

In [21]:
np.average(kfscore)

np.float64(0.6856785107611354)

In [22]:
kfscore1=cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='accuracy')
kfscore1

array([0.76470588, 0.85294118, 0.82352941, 0.67647059, 0.70588235,
       0.81818182, 0.78787879, 0.78787879, 0.78787879, 0.72727273,
       0.72727273, 0.78787879, 0.66666667, 0.78787879, 0.63636364])

In [23]:
np.average(kfscore1)

np.float64(0.7559120617944146)

In [24]:
kf3=StratifiedKFold(n_splits=10,shuffle=True,random_state=11)
kfscore3=cross_val_score(lr,X,y.values.ravel(),cv=kf3,scoring='accuracy')
kfscore3

array([0.66, 0.76, 0.76, 0.8 , 0.8 , 0.74, 0.76, 0.74, 0.78, 0.76])

In [25]:
np.average(kfscore3)

np.float64(0.756)

In [27]:
scale=StandardScaler()
pipe=make_pipeline(scale,lr)
pipe.fit(X_train,y_train.values.ravel())
scoresPipe=cross_val_score(pipe,X,y.values.ravel(),cv=10)
scoresPipe
print(f"Average: {np.average(scoresPipe)}")
print(f"Standard Deviation: {np.std(scoresPipe)}")


Average: 0.756
Standard Deviation: 0.04270831300812523
